FROM nvidia/cuda:11.6.0-runtime-ubuntu20.04
ENV DEBIAN_FRONTEND noninteractive
ARG PYTHON_VERSION=3.8
RUN apt-get update &&\
    apt-get install -y software-properties-common \
    python3-pip &&\
	ln -s /usr/bin/python3.8 /usr/local/bin/python &&\
    	ln -s /usr/bin/python3.8 /usr/local/bin/python3 &&\
	rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
COPY ./requirements.txt ./
RUN pip install -r ./requirements.txt
WORKDIR /workspace/proj
COPY . .
ENTRYPOINT ["python", "main.py"]
